//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baustelle
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaustelleDBEntities : DbContext
    {
        public BaustelleDBEntities()
            : base("name=BaustelleDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JedinicaMjereSet> JedinicaMjereSet { get; set; }
        public virtual DbSet<KlijentSet> KlijentSet { get; set; }
        public virtual DbSet<MaterijalSet> MaterijalSet { get; set; }
        public virtual DbSet<PonudaSet> PonudaSet { get; set; }
        public virtual DbSet<StavkaPonudeSet> StavkaPonudeSet { get; set; }
        public virtual DbSet<StavkaUslugeSet> StavkaUslugeSet { get; set; }
        public virtual DbSet<UlogaSet> UlogaSet { get; set; }
        public virtual DbSet<UslugaSet> UslugaSet { get; set; }
        public virtual DbSet<ZaspolenikSet> ZaspolenikSet { get; set; }
    }
}
