//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baustelle
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseContainer : DbContext
    {
        public DatabaseContainer()
            : base("name=DatabaseContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JedinicaMjere> JedinicaMjereSet { get; set; }
        public virtual DbSet<Materijal> MaterijalSet { get; set; }
        public virtual DbSet<Usluga> UslugaSet { get; set; }
        public virtual DbSet<StavkaUsluge> StavkaUslugeSet { get; set; }
        public virtual DbSet<Zaspolenik> ZaspolenikSet { get; set; }
        public virtual DbSet<Uloga> UlogaSet { get; set; }
        public virtual DbSet<Klijent> KlijentSet { get; set; }
        public virtual DbSet<Ponuda> PonudaSet { get; set; }
        public virtual DbSet<StavkaPonude> StavkaPonudeSet { get; set; }
    }
}
