//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baustelle
{
    using System;
    using System.Collections.Generic;
    
    public partial class JedinicaMjere
    {
        public JedinicaMjere()
        {
            this.Materijal = new HashSet<Materijal>();
        }
    
        public int IdJedinicaMjere { get; set; }
        public string Naziv { get; set; }
        public string SkraceniNaziv { get; set; }
    
        public virtual ICollection<Materijal> Materijal { get; set; }
    }
}
