//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baustelle
{
    using System;
    using System.Collections.Generic;
    
    public partial class KlijentSet
    {
        public KlijentSet()
        {
            this.PonudaSet = new HashSet<PonudaSet>();
        }
    
        public int IdKlijent { get; set; }
        public string Naziv { get; set; }
        public string OIB { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<PonudaSet> PonudaSet { get; set; }
    }
}
