//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baustelle
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterijalSet
    {
        public MaterijalSet()
        {
            this.StavkaUslugeSet = new HashSet<StavkaUslugeSet>();
        }
    
        public int IdMaterijal { get; set; }
        public string Naziv { get; set; }
        public string Napomena { get; set; }
        public int JedinicaMjereId { get; set; }
    
        public virtual JedinicaMjereSet JedinicaMjereSet { get; set; }
        public virtual ICollection<StavkaUslugeSet> StavkaUslugeSet { get; set; }
    }
}
