//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baustelle
{
    using System;
    using System.Collections.Generic;
    
    public partial class PonudaSet
    {
        public PonudaSet()
        {
            this.StavkaPonudeSet = new HashSet<StavkaPonudeSet>();
        }
    
        public int IdPonuda { get; set; }
        public int KlijentId { get; set; }
        public int ZaposlenikId { get; set; }
        public System.DateTime DatumIzdavanja { get; set; }
        public string Napomena { get; set; }
    
        public virtual KlijentSet KlijentSet { get; set; }
        public virtual ICollection<StavkaPonudeSet> StavkaPonudeSet { get; set; }
        public virtual ZaspolenikSet ZaspolenikSet { get; set; }
    }
}
