//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baustelle
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkaUslugeSet
    {
        public int IdStavkaUsluge { get; set; }
        public int UslugaId { get; set; }
        public int MaterijalId { get; set; }
        public decimal Kolicina { get; set; }
    
        public virtual MaterijalSet MaterijalSet { get; set; }
        public virtual UslugaSet UslugaSet { get; set; }
    }
}
