//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baustelle
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZaspolenikSet
    {
        public ZaspolenikSet()
        {
            this.PonudaSet = new HashSet<PonudaSet>();
            this.UslugaSet = new HashSet<UslugaSet>();
        }
    
        public int IdZaposlenik { get; set; }
        public int UlogaId { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public System.DateTime DatumRodjenja { get; set; }
        public string OIB { get; set; }
        public string Adresa { get; set; }
        public string Kontakt { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<PonudaSet> PonudaSet { get; set; }
        public virtual UlogaSet UlogaSet { get; set; }
        public virtual ICollection<UslugaSet> UslugaSet { get; set; }
    }
}
