//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baustelle
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaspolenik
    {
        public Zaspolenik()
        {
            this.Usluga = new HashSet<Usluga>();
            this.Ponuda = new HashSet<Ponuda>();
        }
    
        public int IdZaposlenik { get; set; }
        public int UlogaId { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public System.DateTime DatumRodjenja { get; set; }
        public string OIB { get; set; }
        public string Adresa { get; set; }
        public string Kontakt { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Usluga> Usluga { get; set; }
        public virtual Uloga Uloga { get; set; }
        public virtual ICollection<Ponuda> Ponuda { get; set; }
    }
}
